# Form implementation generated from reading ui file 'UI_UpdateDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateDialog(object):
    def setupUi(self, UpdateDialog):
        UpdateDialog.setObjectName("UpdateDialog")
        UpdateDialog.resize(540, 360)
        UpdateDialog.setWindowFlags(QtCore.Qt.Dialog|QtCore.Qt.WindowCloseButtonHint|QtCore.Qt.MSWindowsFixedSizeDialogHint)
        self.verticalLayout = QtWidgets.QVBoxLayout(UpdateDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=UpdateDialog)
        self.frame.setMinimumSize(QtCore.QSize(540, 360))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 16px;\n"
"box-shadow: 0 10px 30px rgba(0, 0, 0, 0.1);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerWidget = QtWidgets.QWidget(parent=self.frame)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 160))
        self.headerWidget.setStyleSheet(".QWidget#headerWidget{\n"
"background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%);\n"
"border-radius: 16px 16px 0 0;\n"
"position: relative;\n"
"overflow: hidden;\n"
"}\n"
"\n"
".QWidget#headerWidget::before {\n"
"content: \'\';\n"
"position: absolute;\n"
"width: 300px;\n"
"height: 300px;\n"
"background: rgba(255, 255, 255, 0.1);\n"
"border-radius: 50%;    op: -150px;\n"
"right: -150px;\n"
"}\n"
"\n"
".QWidget#headerWidget::after {\n"
"content: \'\';\n"
"position: absolute;\n"
"width: 150px;\n"
"height: 150px;\n"
"background: rgba(255, 255, 255, 0.15);\n"
"border-radius: 50%;\n"
"bottom: -75px;\n"
"left: -75px;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.headerWidget)
        self.verticalLayout_3.setContentsMargins(32, 32, 32, 24)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"}")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.label_version = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgba(255, 255, 255, 0.9);")
        self.label_version.setObjectName("label_version")
        self.verticalLayout_3.addWidget(self.label_version)
        self.verticalLayout_2.addWidget(self.headerWidget)
        self.contentWidget = QtWidgets.QWidget(parent=self.frame)
        self.contentWidget.setStyleSheet(".QWidget#contentWidget {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0 0 16px 16px;\n"
"}\n"
"\n"
"QLabel#label_content {\n"
"color: #4B5563;\n"
"line-height: 1.5;\n"
"}")
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_4.setContentsMargins(32, 24, 32, 24)
        self.verticalLayout_4.setSpacing(24)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_content = QtWidgets.QLabel(parent=self.contentWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_content.setFont(font)
        self.label_content.setWordWrap(True)
        self.label_content.setObjectName("label_content")
        self.verticalLayout_4.addWidget(self.label_content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.contentWidget)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #F3F4F6;\n"
"    color: #4B5563;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #E5E7EB;\n"
"    transform: translateY(-1px);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #D1D5DB;\n"
"    transform: translateY(0);\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_download = QtWidgets.QPushButton(parent=self.contentWidget)
        self.pushButton_download.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton_download.setMaximumSize(QtCore.QSize(120, 40))
        self.pushButton_download.setStyleSheet("QPushButton {\n"
"    background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    box-shadow: 0 4px 12px rgba(99, 102, 241, 0.3);\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    box-shadow: 0 6px 16px rgba(99, 102, 241, 0.4);\n"
"    transform: translateY(-2px);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    box-shadow: 0 2px 8px rgba(99, 102, 241, 0.3);\n"
"    transform: translateY(0);\n"
"}")
        self.pushButton_download.setObjectName("pushButton_download")
        self.horizontalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.contentWidget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(UpdateDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateDialog)

    def retranslateUi(self, UpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateDialog.setWindowTitle(_translate("UpdateDialog", "更新提示"))
        self.label_title.setText(_translate("UpdateDialog", "新版本已发布"))
        self.label_version.setText(_translate("UpdateDialog", "LeafView v2.0.0"))
        self.label_content.setText(_translate("UpdateDialog", "发现新版本！这次更新带来了性能优化和全新功能体验，建议立即更新以获得更好的使用体验。"))
        self.pushButton_cancel.setText(_translate("UpdateDialog", "暂不更新"))
        self.pushButton_download.setText(_translate("UpdateDialog", "立即更新"))
