# Form implementation generated from reading ui file 'UI_UpdateDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateDialog(object):
    def setupUi(self, UpdateDialog):
        UpdateDialog.setObjectName("UpdateDialog")
        UpdateDialog.resize(600, 480)
        UpdateDialog.setModal(True)
        UpdateDialog.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.verticalLayout = QtWidgets.QVBoxLayout(UpdateDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=UpdateDialog)
        self.frame.setMinimumSize(QtCore.QSize(600, 480))
        self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 24px;\n"
"box-shadow: 0px 20px 40px rgba(0, 0, 0, 0.15);\n"
"border: 1px solid rgba(0, 0, 0, 0.08);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headerWidget = QtWidgets.QWidget(parent=self.frame)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.headerWidget.setStyleSheet(".QWidget#headerWidget{\n"
"background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%);\n"
"border-radius: 24px 24px 0 0;\n"
"position: relative;\n"
"overflow: hidden;\n"
"}\n"
"\n"
".QWidget#headerWidget::before {\n"
"content: \'\';\n"
"position: absolute;\n"
"width: 400px;\n"
"height: 400px;\n"
"background: rgba(255, 255, 255, 0.12);\n"
"border-radius: 50%;\n"
"top: -200px;\n"
"right: -200px;\n"
"animation: pulse 8s ease-in-out infinite;\n"
"}\n"
"\n"
".QWidget#headerWidget::after {\n"
"content: \'\';\n"
"position: absolute;\n"
"width: 200px;\n"
"height: 200px;\n"
"background: rgba(255, 255, 255, 0.08);\n"
"border-radius: 50%;\n"
"bottom: -100px;\n"
"left: -100px;\n"
"animation: pulse 6s ease-in-out infinite alternate;\n"
"}\n"
"\n"
"@keyframes pulse {\n"
"0%, 100% { opacity: 0.6; transform: scale(1); }\n"
"50% { opacity: 0.8; transform: scale(1.05); }\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.headerWidget)
        self.verticalLayout_3.setContentsMargins(48, 48, 48, 36)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_icon = QtWidgets.QLabel(parent=self.headerWidget)
        self.label_icon.setMinimumSize(QtCore.QSize(56, 56))
        self.label_icon.setMaximumSize(QtCore.QSize(56, 56))
        self.label_icon.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"    border-radius: 16px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    font-family: \'Segoe UI Symbol\';\n"
"    font-size: 28px;\n"
"    color: white;\n"
"}")
        self.label_icon.setObjectName("label_icon")
        self.verticalLayout_3.addWidget(self.label_icon)
        self.label_title = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-alignment: \'AlignLeft\';\n"
"    letter-spacing: 0.5px;\n"
"}")
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.label_version = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgba(255, 255, 255, 0.85);\n"
"font-weight: 500;\n"
"letter-spacing: 0.3px;")
        self.label_version.setObjectName("label_version")
        self.verticalLayout_3.addWidget(self.label_version)
        self.verticalLayout_2.addWidget(self.headerWidget)
        self.contentWidget = QtWidgets.QWidget(parent=self.frame)
        self.contentWidget.setStyleSheet(".QWidget#contentWidget {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 0 0 24px 24px;\n"
"}\n"
"\n"
"QLabel#label_content {\n"
"color: #374151;\n"
"line-height: 1.7;\n"
"font-size: 15px;\n"
"font-weight: 400;\n"
"}")
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_4.setContentsMargins(48, 36, 48, 36)
        self.verticalLayout_4.setSpacing(36)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_content = QtWidgets.QLabel(parent=self.contentWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        self.label_content.setFont(font)
        self.label_content.setWordWrap(True)
        self.label_content.setObjectName("label_content")
        self.verticalLayout_4.addWidget(self.label_content)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(parent=self.contentWidget)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(120, 48))
        self.pushButton_cancel.setMaximumSize(QtCore.QSize(120, 48))
        self.pushButton_cancel.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_cancel.setStyleSheet("QPushButton {\n"
"    background-color: #F9FAFB;\n"
"    color: #6B7280;\n"
"    border: 1px solid #E5E7EB;\n"
"    border-radius: 12px;\n"
"    font-family: \'Microsoft YaHei UI\';\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    padding: 8px 16px;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F3F4F6;\n"
"    border-color: #D1D5DB;\n"
"    color: #374151;\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.08);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E5E7EB;\n"
"    border-color: #9CA3AF;\n"
"    transform: translateY(0px);\n"
"    box-shadow: 0px 2px 6px rgba(0, 0, 0, 0.05);\n"
"}")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_download = QtWidgets.QPushButton(parent=self.contentWidget)
        self.pushButton_download.setMinimumSize(QtCore.QSize(140, 48))
        self.pushButton_download.setMaximumSize(QtCore.QSize(140, 48))
        self.pushButton_download.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_download.setStyleSheet("QPushButton {\n"
"    background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    font-family: \'Microsoft YaHei UI\';\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    padding: 8px 20px;\n"
"    transition: all 0.2s ease;\n"
"    box-shadow: 0px 6px 16px rgba(99, 102, 241, 0.3);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%);\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0px 8px 20px rgba(99, 102, 241, 0.4);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: linear-gradient(135deg, #4338CA 0%, #6D28D9 100%);\n"
"    transform: translateY(0px);\n"
"    box-shadow: 0px 4px 12px rgba(99, 102, 241, 0.3);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #9CA3AF;\n"
"    box-shadow: none;\n"
"}")
        self.pushButton_download.setObjectName("pushButton_download")
        self.horizontalLayout.addWidget(self.pushButton_download)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.contentWidget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(UpdateDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateDialog)

    def retranslateUi(self, UpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateDialog.setWindowTitle(_translate("UpdateDialog", "更新提示"))
        self.label_icon.setText(_translate("UpdateDialog", "🔄"))
        self.label_title.setText(_translate("UpdateDialog", "发现新版本"))
        self.label_version.setText(_translate("UpdateDialog", "LeafView v2.0.0 现已可用"))
        self.label_content.setText(_translate("UpdateDialog", "🎉 我们很高兴为您带来 LeafView v2.0.0！本次更新包含：\n"
"\n"
"• 性能优化：启动速度提升40%\n"
"• 全新功能：智能图片整理和AI识别\n"
"• 界面改进：更流畅的操作体验\n"
"• 稳定性：修复了多个已知问题\n"
"\n"
"建议立即更新以获得最佳体验！"))
        self.pushButton_cancel.setText(_translate("UpdateDialog", "稍后提醒"))
        self.pushButton_download.setText(_translate("UpdateDialog", "立即更新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateDialog = QtWidgets.QDialog()
    ui = Ui_UpdateDialog()
    ui.setupUi(UpdateDialog)
    UpdateDialog.show()
    sys.exit(app.exec())
