# Form implementation generated from reading ui file 'UI_UpdateDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateDialog(object):
    def setupUi(self, UpdateDialog):
        UpdateDialog.setObjectName("UpdateDialog")
        UpdateDialog.resize(512, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        UpdateDialog.setWindowIcon(icon)
        self.mainLayout = QtWidgets.QVBoxLayout(UpdateDialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.backgroundFrame = QtWidgets.QFrame(parent=UpdateDialog)
        self.backgroundFrame.setMinimumSize(QtCore.QSize(512, 320))
        self.backgroundFrame.setStyleSheet("QFrame#backgroundFrame {\n"
"    background-color: #f5f9fe;\n"
"    border-radius: 25px;\n"
"}")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.contentLayout = QtWidgets.QHBoxLayout(self.backgroundFrame)
        self.contentLayout.setContentsMargins(0, 0, 0, 0)
        self.contentLayout.setSpacing(12)
        self.contentLayout.setObjectName("contentLayout")
        self.dialogLayout = QtWidgets.QVBoxLayout()
        self.dialogLayout.setContentsMargins(9, 9, 9, 9)
        self.dialogLayout.setSpacing(0)
        self.dialogLayout.setObjectName("dialogLayout")
        self.headerWidget = QtWidgets.QWidget(parent=self.backgroundFrame)
        self.headerWidget.setStyleSheet("QWidget#headerWidget {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #691bfd, \n"
"                                      stop: 1 #c8a0f0);\n"
"    border-radius: 16px;\n"
"    color: #ffffff;\n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerWidget)
        self.headerLayout.setContentsMargins(18, 18, 18, 18)
        self.headerLayout.setSpacing(18)
        self.headerLayout.setObjectName("headerLayout")
        self.messageLayout = QtWidgets.QHBoxLayout()
        self.messageLayout.setObjectName("messageLayout")
        self.textLayout = QtWidgets.QVBoxLayout()
        self.textLayout.setSpacing(0)
        self.textLayout.setObjectName("textLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("QLabel#titleLabel {\n"
"    color: #deffff;\n"
"    text-align: center;\n"
"    margin-bottom: 12px;\n"
"}")
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.textLayout.addWidget(self.titleLabel)
        self.messageLabel = QtWidgets.QLabel(parent=self.headerWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.messageLabel.setFont(font)
        self.messageLabel.setStyleSheet("QLabel#messageLabel {\n"
"    color: #fafafa;\n"
"    text-align: left;\n"
"}")
        self.messageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.messageLabel.setWordWrap(True)
        self.messageLabel.setObjectName("messageLabel")
        self.textLayout.addWidget(self.messageLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setContentsMargins(-1, -1, 6, -1)
        self.buttonLayout.setSpacing(12)
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(parent=self.headerWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(88, 30))
        self.cancelButton.setMaximumSize(QtCore.QSize(88, 30))
        self.cancelButton.setStyleSheet("QPushButton#cancelButton {\n"
"    background-color: rgba(250, 250, 250, 100);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 12px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton#cancelButton:hover {\n"
"    background-color: rgba(250, 250, 250, 130);\n"
"}\n"
"\n"
"QPushButton#cancelButton:pressed {\n"
"    background-color: rgba(250, 250, 250, 180);\n"
"}\n"
"\n"
"QPushButton#cancelButton:disabled {\n"
"    background-color: rgba(250, 250, 250, 50);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}")
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.updateButton = QtWidgets.QPushButton(parent=self.headerWidget)
        self.updateButton.setMinimumSize(QtCore.QSize(88, 30))
        self.updateButton.setMaximumSize(QtCore.QSize(88, 30))
        self.updateButton.setStyleSheet("QPushButton#updateButton {\n"
"    background-color: rgba(105, 27, 253, 180);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-size: 12px;\n"
"    font-weight: normal;\n"
"}\n"
"\n"
"QPushButton#updateButton:hover {\n"
"    background-color: rgba(105, 27, 253, 120);\n"
"}\n"
"\n"
"QPushButton#updateButton:pressed {\n"
"    background-color: rgba(105, 27, 253, 250);\n"
"}\n"
"\n"
"QPushButton#updateButton:disabled {\n"
"    background-color: rgba(105, 27, 253, 50);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}")
        self.updateButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.updateButton.setDefault(True)
        self.updateButton.setObjectName("updateButton")
        self.buttonLayout.addWidget(self.updateButton)
        self.textLayout.addLayout(self.buttonLayout)
        self.textLayout.setStretch(0, 1)
        self.textLayout.setStretch(1, 3)
        self.textLayout.setStretch(2, 1)
        self.messageLayout.addLayout(self.textLayout)
        self.headerLayout.addLayout(self.messageLayout)
        self.headerLayout.setStretch(0, 5)
        self.dialogLayout.addWidget(self.headerWidget)
        self.dialogLayout.setStretch(0, 9)
        self.contentLayout.addLayout(self.dialogLayout)
        self.contentLayout.setStretch(0, 4)
        self.mainLayout.addWidget(self.backgroundFrame)

        self.retranslateUi(UpdateDialog)
        QtCore.QMetaObject.connectSlotsByName(UpdateDialog)

    def retranslateUi(self, UpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        UpdateDialog.setWindowTitle(_translate("UpdateDialog", "软件更新"))
        self.titleLabel.setText(_translate("UpdateDialog", "发现新版本"))
        self.messageLabel.setText(_translate("UpdateDialog", "有新版本可用，是否立即下载更新？"))
        self.cancelButton.setText(_translate("UpdateDialog", "暂不更新"))
        self.updateButton.setText(_translate("UpdateDialog", "立即下载"))
