# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        
        # 创建中央部件
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 创建主布局
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        
        # 创建标题栏
        self.titleBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.titleBar.setObjectName("titleBar")
        self.titleBar.setFixedHeight(40)
        
        # 创建标题栏布局
        self.titleBarLayout = QtWidgets.QHBoxLayout(self.titleBar)
        self.titleBarLayout.setContentsMargins(10, 0, 10, 0)
        
        # 创建应用图标
        self.appIcon = QtWidgets.QLabel(parent=self.titleBar)
        self.appIcon.setObjectName("appIcon")
        
        # 创建应用标题
        self.appTitle = QtWidgets.QLabel(parent=self.titleBar)
        self.appTitle.setObjectName("appTitle")
        
        # 创建窗口控制按钮
        self.minimizeButton = QtWidgets.QPushButton(parent=self.titleBar)
        self.minimizeButton.setObjectName("minimizeButton")
        self.minimizeButton.setFixedSize(30, 30)
        
        self.maximizeButton = QtWidgets.QPushButton(parent=self.titleBar)
        self.maximizeButton.setObjectName("maximizeButton")
        self.maximizeButton.setFixedSize(30, 30)
        
        self.closeButton = QtWidgets.QPushButton(parent=self.titleBar)
        self.closeButton.setObjectName("closeButton")
        self.closeButton.setFixedSize(30, 30)
        
        # 添加到标题栏布局
        self.titleBarLayout.addWidget(self.appIcon)
        self.titleBarLayout.addWidget(self.appTitle)
        self.titleBarLayout.addStretch()
        self.titleBarLayout.addWidget(self.minimizeButton)
        self.titleBarLayout.addWidget(self.maximizeButton)
        self.titleBarLayout.addWidget(self.closeButton)
        
        # 创建内容区域
        self.contentContainer = QtWidgets.QFrame(parent=self.centralwidget)
        self.contentContainer.setObjectName("contentContainer")
        
        # 创建内容布局
        self.contentLayout = QtWidgets.QHBoxLayout(self.contentContainer)
        self.contentLayout.setContentsMargins(0, 0, 0, 0)
        self.contentLayout.setSpacing(0)
        
        # 创建导航栏
        self.navigationFrame = QtWidgets.QFrame(parent=self.contentContainer)
        self.navigationFrame.setObjectName("navigationFrame")
        self.navigationFrame.setFixedWidth(200)
        
        # 创建导航栏布局
        self.navigationLayout = QtWidgets.QVBoxLayout(self.navigationFrame)
        self.navigationLayout.setContentsMargins(10, 20, 10, 20)
        self.navigationLayout.setSpacing(10)
        
        # 创建导航按钮
        self.mediaButton = QtWidgets.QPushButton(parent=self.navigationFrame)
        self.mediaButton.setObjectName("mediaButton")
        self.mediaButton.setFixedHeight(40)
        
        self.classificationButton = QtWidgets.QPushButton(parent=self.navigationFrame)
        self.classificationButton.setObjectName("classificationButton")
        self.classificationButton.setFixedHeight(40)
        
        self.duplicatesButton = QtWidgets.QPushButton(parent=self.navigationFrame)
        self.duplicatesButton.setObjectName("duplicatesButton")
        self.duplicatesButton.setFixedHeight(40)
        
        # 添加到导航栏布局
        self.navigationLayout.addWidget(self.mediaButton)
        self.navigationLayout.addWidget(self.classificationButton)
        self.navigationLayout.addWidget(self.duplicatesButton)
        self.navigationLayout.addStretch()
        
        # 创建主内容区
        self.mainContentFrame = QtWidgets.QFrame(parent=self.contentContainer)
        self.mainContentFrame.setObjectName("mainContentFrame")
        
        # 创建主内容布局
        self.mainContentLayout = QtWidgets.QVBoxLayout(self.mainContentFrame)
        self.mainContentLayout.setContentsMargins(10, 10, 10, 10)
        
        # 创建堆叠窗口
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainContentFrame)
        
        # 创建媒体页面
        self.mediaPage = QtWidgets.QWidget()
        self.mediaPage.setObjectName("mediaPage")
        self.mediaPageLayout = QtWidgets.QVBoxLayout(self.mediaPage)
        self.mediaPageLayout.setContentsMargins(0, 0, 0, 0)
        
        # 创建媒体页面工具栏
        self.mediaToolbar = QtWidgets.QFrame(parent=self.mediaPage)
        self.mediaToolbar.setObjectName("mediaToolbar")
        self.mediaToolbar.setFixedHeight(50)
        
        # 创建媒体页面工具栏布局
        self.mediaToolbarLayout = QtWidgets.QHBoxLayout(self.mediaToolbar)
        self.mediaToolbarLayout.setContentsMargins(10, 10, 10, 10)
        
        # 创建媒体页面工具栏按钮
        self.addFolderButton = QtWidgets.QPushButton(parent=self.mediaToolbar)
        self.addFolderButton.setObjectName("addFolderButton")
        
        self.removeFolderButton = QtWidgets.QPushButton(parent=self.mediaToolbar)
        self.removeFolderButton.setObjectName("removeFolderButton")
        
        self.refreshButton = QtWidgets.QPushButton(parent=self.mediaToolbar)
        self.refreshButton.setObjectName("refreshButton")
        
        # 添加到媒体页面工具栏布局
        self.mediaToolbarLayout.addWidget(self.addFolderButton)
        self.mediaToolbarLayout.addWidget(self.removeFolderButton)
        self.mediaToolbarLayout.addWidget(self.refreshButton)
        self.mediaToolbarLayout.addStretch()
        
        # 添加到媒体页面布局
        self.mediaPageLayout.addWidget(self.mediaToolbar)
        
        # 创建分类页面
        self.classificationPage = QtWidgets.QWidget()
        self.classificationPage.setObjectName("classificationPage")
        self.classificationPageLayout = QtWidgets.QVBoxLayout(self.classificationPage)
        self.classificationPageLayout.setContentsMargins(0, 0, 0, 0)
        
        # 创建分类页面工具栏
        self.classificationToolbar = QtWidgets.QFrame(parent=self.classificationPage)
        self.classificationToolbar.setObjectName("classificationToolbar")
        self.classificationToolbar.setFixedHeight(50)
        
        # 创建分类页面工具栏布局
        self.classificationToolbarLayout = QtWidgets.QHBoxLayout(self.classificationToolbar)
        self.classificationToolbarLayout.setContentsMargins(10, 10, 10, 10)
        
        # 创建分类页面工具栏按钮
        self.classifyButton = QtWidgets.QPushButton(parent=self.classificationToolbar)
        self.classifyButton.setObjectName("classifyButton")
        
        self.stopClassificationButton = QtWidgets.QPushButton(parent=self.classificationToolbar)
        self.stopClassificationButton.setObjectName("stopClassificationButton")
        
        # 添加到分类页面工具栏布局
        self.classificationToolbarLayout.addWidget(self.classifyButton)
        self.classificationToolbarLayout.addWidget(self.stopClassificationButton)
        self.classificationToolbarLayout.addStretch()
        
        # 添加到分类页面布局
        self.classificationPageLayout.addWidget(self.classificationToolbar)
        
        # 创建去重页面
        self.duplicatesPage = QtWidgets.QWidget()
        self.duplicatesPage.setObjectName("duplicatesPage")
        self.duplicatesPageLayout = QtWidgets.QVBoxLayout(self.duplicatesPage)
        self.duplicatesPageLayout.setContentsMargins(0, 0, 0, 0)
        
        # 创建去重页面工具栏
        self.duplicatesToolbar = QtWidgets.QFrame(parent=self.duplicatesPage)
        self.duplicatesToolbar.setObjectName("duplicatesToolbar")
        self.duplicatesToolbar.setFixedHeight(50)
        
        # 创建去重页面工具栏布局
        self.duplicatesToolbarLayout = QtWidgets.QHBoxLayout(self.duplicatesToolbar)
        self.duplicatesToolbarLayout.setContentsMargins(10, 10, 10, 10)
        
        # 创建去重页面工具栏按钮
        self.startDuplicateButton = QtWidgets.QPushButton(parent=self.duplicatesToolbar)
        self.startDuplicateButton.setObjectName("startDuplicateButton")
        
        self.stopDuplicateButton = QtWidgets.QPushButton(parent=self.duplicatesToolbar)
        self.stopDuplicateButton.setObjectName("stopDuplicateButton")
        
        self.applyDuplicateButton = QtWidgets.QPushButton(parent=self.duplicatesToolbar)
        self.applyDuplicateButton.setObjectName("applyDuplicateButton")
        
        # 添加到去重页面工具栏布局
        self.duplicatesToolbarLayout.addWidget(self.startDuplicateButton)
        self.duplicatesToolbarLayout.addWidget(self.stopDuplicateButton)
        self.duplicatesToolbarLayout.addWidget(self.applyDuplicateButton)
        self.duplicatesToolbarLayout.addStretch()
        
        # 添加到去重页面布局
        self.duplicatesPageLayout.addWidget(self.duplicatesToolbar)
        
        # 添加页面到堆叠窗口
        self.stackedWidget.addWidget(self.mediaPage)
        self.stackedWidget.addWidget(self.classificationPage)
        self.stackedWidget.addWidget(self.duplicatesPage)
        
        # 添加到主内容布局
        self.mainContentLayout.addWidget(self.stackedWidget)
        
        # 添加到内容布局
        self.contentLayout.addWidget(self.navigationFrame)
        self.contentLayout.addWidget(self.mainContentFrame, 1)
        
        # 创建状态栏
        self.statusBar = QtWidgets.QFrame(parent=self.centralwidget)
        self.statusBar.setObjectName("statusBar")
        self.statusBar.setFixedHeight(30)
        
        # 创建状态栏布局
        self.statusBarLayout = QtWidgets.QHBoxLayout(self.statusBar)
        self.statusBarLayout.setContentsMargins(10, 0, 10, 0)
        
        # 创建状态标签
        self.statusLabel = QtWidgets.QLabel(parent=self.statusBar)
        self.statusLabel.setObjectName("statusLabel")
        
        # 添加到状态栏布局
        self.statusBarLayout.addWidget(self.statusLabel)
        self.statusBarLayout.addStretch()
        
        # 添加到主布局
        self.mainLayout.addWidget(self.titleBar)
        self.mainLayout.addWidget(self.contentContainer, 1)
        self.mainLayout.addWidget(self.statusBar)
        
        # 设置中央部件
        MainWindow.setCentralWidget(self.centralwidget)
        
        # 设置窗口标题
        MainWindow.setWindowTitle("LeafView - 媒体管理工具")
        
        # 设置对象名称
        MainWindow.setObjectName("MainWindow")
        
        # 设置样式表
        self._setup_styles()
    
    def _setup_styles(self):
        """设置样式表"""
        # 标题栏样式
        self.titleBar.setStyleSheet("""
            QFrame#titleBar {
                background-color: #2c3e50;
                border-bottom: 1px solid #1a252f;
            }
        """)
        
        # 应用标题样式
        self.appTitle.setStyleSheet("""
            QLabel#appTitle {
                color: white;
                font-size: 16px;
                font-weight: bold;
            }
        """)
        
        # 窗口控制按钮样式
        self.minimizeButton.setStyleSheet("""
            QPushButton#minimizeButton {
                background-color: transparent;
                border: none;
                border-radius: 4px;
            }
            QPushButton#minimizeButton:hover {
                background-color: #34495e;
            }
        """)
        
        self.maximizeButton.setStyleSheet("""
            QPushButton#maximizeButton {
                background-color: transparent;
                border: none;
                border-radius: 4px;
            }
            QPushButton#maximizeButton:hover {
                background-color: #34495e;
            }
        """)
        
        self.closeButton.setStyleSheet("""
            QPushButton#closeButton {
                background-color: transparent;
                border: none;
                border-radius: 4px;
            }
            QPushButton#closeButton:hover {
                background-color: #e74c3c;
            }
        """)
        
        # 内容区域样式
        self.contentContainer.setStyleSheet("""
            QFrame#contentContainer {
                background-color: #ecf0f1;
            }
        """)
        
        # 导航栏样式
        self.navigationFrame.setStyleSheet("""
            QFrame#navigationFrame {
                background-color: #34495e;
                border-right: 1px solid #2c3e50;
            }
        """)
        
        # 导航按钮样式
        self.mediaButton.setStyleSheet("""
            QPushButton#mediaButton {
                background-color: #3498db;
                color: white;
                border: none;
                border-radius: 5px;
                text-align: left;
                padding-left: 10px;
                font-weight: bold;
            }
            QPushButton#mediaButton:hover {
                background-color: #2980b9;
            }
        """)
        
        self.classificationButton.setStyleSheet("""
            QPushButton#classificationButton {
                background-color: #34495e;
                color: white;
                border: none;
                border-radius: 5px;
                text-align: left;
                padding-left: 10px;
            }
            QPushButton#classificationButton:hover {
                background-color: #2c3e50;
            }
        """)
        
        self.duplicatesButton.setStyleSheet("""
            QPushButton#duplicatesButton {
                background-color: #34495e;
                color: white;
                border: none;
                border-radius: 5px;
                text-align: left;
                padding-left: 10px;
            }
            QPushButton#duplicatesButton:hover {
                background-color: #2c3e50;
            }
        """)
        
        # 主内容区样式
        self.mainContentFrame.setStyleSheet("""
            QFrame#mainContentFrame {
                background-color: white;
                border-radius: 5px;
            }
        """)
        
        # 状态栏样式
        self.statusBar.setStyleSheet("""
            QFrame#statusBar {
                background-color: #34495e;
                border-top: 1px solid #2c3e50;
            }
        """)
        
        # 状态标签样式
        self.statusLabel.setStyleSheet("""
            QLabel#statusLabel {
                color: white;
            }
        """)
        
        # 工具栏样式
        self.mediaToolbar.setStyleSheet("""
            QFrame#mediaToolbar {
                background-color: #f8f9fa;
                border-bottom: 1px solid #dee2e6;
                border-radius: 5px;
            }
        """)
        
        self.classificationToolbar.setStyleSheet("""
            QFrame#classificationToolbar {
                background-color: #f8f9fa;
                border-bottom: 1px solid #dee2e6;
                border-radius: 5px;
            }
        """)
        
        self.duplicatesToolbar.setStyleSheet("""
            QFrame#duplicatesToolbar {
                background-color: #f8f9fa;
                border-bottom: 1px solid #dee2e6;
                border-radius: 5px;
            }
        """)
        
        # 工具栏按钮样式
        self.addFolderButton.setStyleSheet("""
            QPushButton {
                background-color: #3498db;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #2980b9;
            }
        """)
        
        self.removeFolderButton.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
        """)
        
        self.refreshButton.setStyleSheet("""
            QPushButton {
                background-color: #2ecc71;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
        """)
        
        self.classifyButton.setStyleSheet("""
            QPushButton {
                background-color: #3498db;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #2980b9;
            }
        """)
        
        self.stopClassificationButton.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
        """)
        
        self.startDuplicateButton.setStyleSheet("""
            QPushButton {
                background-color: #3498db;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #2980b9;
            }
        """)
        
        self.stopDuplicateButton.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
        """)
        
        self.applyDuplicateButton.setStyleSheet("""
            QPushButton {
                background-color: #2ecc71;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 5px 10px;
            }
            QPushButton:hover {
                background-color: #27ae60;
            }
        """)
        
        # 设置按钮文本
        self.mediaButton.setText("媒体管理")
        self.classificationButton.setText("分类管理")
        self.duplicatesButton.setText("去重管理")
        self.addFolderButton.setText("添加文件夹")
        self.removeFolderButton.setText("移除文件夹")
        self.refreshButton.setText("刷新")
        self.classifyButton.setText("开始分类")
        self.stopClassificationButton.setText("停止分类")
        self.startDuplicateButton.setText("开始去重")
        self.stopDuplicateButton.setText("停止去重")
        self.applyDuplicateButton.setText("应用结果")
        self.appTitle.setText("LeafView")
        self.statusLabel.setText("就绪")